version: "3"
services:

  frontend_uniformes:
    container_name: uniformes-frontend
    image: coad2019/uniformes-frontend
    env_file: .env
    depends_on:
      - db_uniformes
      - api_uniformes

  db_uniformes:
    container_name: database
    image: postgres:11.2-alpine
    restart: always
    env_file: .env
    volumes:
      - ../hom-postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  api_uniformes:
    container_name: uniformes-backend
    image: coad2019/uniformes-api
    command: "gunicorn config.wsgi:application --bind=0.0.0.0:8001 -w 8"
    env_file: .env
    ports:
      - 8001:8000
    depends_on:
      - db_uniformes
      - redis_uniformes
    volumes:
      - ../SME-Proxy/django_media_uniformes:/code/sme_uniforme_apps/media
      - ../SME-Proxy/django_static_uniformes:/code/staticfiles

  celery_uniformes:
    container_name: celery_uniformes
    restart: always
    image: coad2019/uniformes-api
    command: "celery -A config worker --loglevel=info --concurrency=3 -n worker1@%h"
    env_file: .env
    depends_on:
      - redis_uniformes


  redis_uniformes:
    container_name: redis_uniformes
    image: redis:5.0.0-alpine
    ports:
      - "6377:6379"

networks:
  default:
    external:
      name: coad-network
